### ISSUE TITLE
Can't edit non-ASCII issue title: UnicodeEncodeError: 'ascii' codec can't encode character ...

### ISSUE THREAD

**Issue by jwilk** [sociomantic-tsunami/git-hub#236]
```console
$ git -c hub.upstream=jwilk/fbcat hub issue update --edit 15
Traceback (most recent call last):
  File ".../git-hub", line 2160, in <module>
    main()
  File ".../git-hub", line 2154, in main
    args.run(parser, args)
  File ".../git-hub", line 649, in check_config_and_run
    cmd.run(parser, args)
  File ".../git-hub", line 1261, in run
    msg = cls.editor(msg)
  File ".../git-hub", line 1080, in editor
    return editor(cls.help_msg, msg)
  File ".../git-hub", line 300, in editor
    f.write(msg or '')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 0: ordinal not in range(128)
```
Tested with git HEAD (08550204e21b42bd7eefc54895844bdc7b46ec77).

**Comment by llucax** [comment]
I think this should be probably fixed by #278 or the move to Python3. Could you confirm?
