### ISSUE TITLE
issue update --edit: NameError: name 'url' is not defined

### ISSUE THREAD

**Issue by jwilk** [sociomantic-tsunami/git-hub#304]
```console
$ git hub issue update --edit 1
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2255, in <module>
    main()
  File "/usr/bin/git-hub", line 2247, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 684, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 1298, in run
    issue = req.get(url)
NameError: name 'url' is not defined
```

**Comment by llucax** [comment]
Mmm, interesting, this was broken around 3 years ago by e29cdd2aa88f37c4ec1fa6866c2a389402101103.
