### ISSUE TITLE
clone: Allow cloning a repo that doesn't have a parent (a personal "blessed" repo)

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/git-hub#43]
Traceback:

```
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 1534, in <module>
    main()
  File "/usr/bin/git-hub", line 1528, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 616, in run
    repo_url = repo['parent'][config.urltype]
KeyError: 'parent'
```

Problem is that own repo is not a fork and thus can't have upstream/parent

**Comment by jwilk** [comment]
For completeness, this is the invocation that failed for me:

```
$ git hub clone jwilk/didjvu
Forking jwilk/didjvu to jwilk/didjvu
Cloning git@github.com:jwilk/didjvu.git to didjvu
Traceback (most recent call last):
  File "/usr/bin/git-hub", line 2003, in <module>
    main()
  File "/usr/bin/git-hub", line 1997, in main
    args.run(parser, args)
  File "/usr/bin/git-hub", line 614, in check_config_and_run
    cmd.run(parser, args)
  File "/usr/bin/git-hub", line 799, in run
    remote_url = repo['parent'][config.urltype]
KeyError: 'parent'
```

OTOH cloning your own repo works if you omit the "<owner>/" part:

```
$ git hub clone didjvu
Warning: Repository jwilk/didjvu is not a fork, just clonning, upstream will not be set
Cloning git@github.com:jwilk/didjvu.git to didjvu
```

The latter doesn't set `hub.upstream`, even though it probably wouldn't hurt if it did.
